<?php
require 'config.php'; login_required(); $pdo=db();
$totalRequests=(int)$pdo->query("SELECT COUNT(*) FROM requests")->fetchColumn();
$pendingRequests=(int)$pdo->query("SELECT COUNT(*) FROM requests WHERE status='pending'")->fetchColumn();
$approvedRequests=(int)$pdo->query("SELECT COUNT(*) FROM requests WHERE status='approved'")->fetchColumn();
$issuedCount=(int)$pdo->query("SELECT COUNT(*) FROM requests WHERE status='issued'")->fetchColumn();
$lowStock=(int)$pdo->query("SELECT COUNT(*) FROM materials WHERE active=1 AND stock > 0 AND stock < 10")->fetchColumn();
$outOfStock=(int)$pdo->query("SELECT COUNT(*) FROM materials WHERE active=1 AND stock <= 0")->fetchColumn();
$materialsCount=(int)$pdo->query("SELECT COUNT(*) FROM materials WHERE active=1")->fetchColumn();
$totalStock=(float)$pdo->query("SELECT COALESCE(SUM(stock),0) FROM materials WHERE active=1")->fetchColumn();
$recent=$pdo->query("SELECT r.*,u.name requester FROM requests r JOIN users u ON u.id=r.requester_id ORDER BY r.id DESC LIMIT 6")->fetchAll();
$monthRequests=(int)$pdo->query("SELECT COUNT(*) FROM requests WHERE YEAR(created_at)=YEAR(CURDATE()) AND MONTH(created_at)=MONTH(CURDATE())")->fetchColumn();
$monthApproved=(int)$pdo->query("SELECT COUNT(*) FROM requests WHERE status IN ('approved','issued') AND YEAR(updated_at)=YEAR(CURDATE()) AND MONTH(updated_at)=MONTH(CURDATE())")->fetchColumn();
$deptStats=$pdo->query("SELECT COALESCE(NULLIF(department,''),'ไม่ระบุ') department, COUNT(*) total FROM requests GROUP BY department ORDER BY total DESC LIMIT 5")->fetchAll();
$stepStats=$pdo->query("SELECT level_no, role_code, status, COUNT(*) total FROM approval_steps GROUP BY level_no,role_code,status ORDER BY level_no")->fetchAll();
$pipeline=[]; foreach($stepStats as $s){ $k=$s['level_no']; if(!isset($pipeline[$k])) $pipeline[$k]=['role'=>$s['role_code'],'pending'=>0,'approved'=>0,'rejected'=>0]; $pipeline[$k][$s['status']]=(int)$s['total']; }
$topVendors=$pdo->query("SELECT v.name,COUNT(p.id) po_count,COALESCE(SUM(p.total_amount),0) total_spend FROM vendors v LEFT JOIN purchase_orders p ON p.vendor_id=v.id AND p.status<>'cancelled' GROUP BY v.id ORDER BY total_spend DESC,po_count DESC LIMIT 5")->fetchAll();
$approvalRate=$totalRequests?round(($approvedRequests+$issuedCount)/$totalRequests*100):0;
$issuedRate=$totalRequests?round($issuedCount/$totalRequests*100):0;
function roleLabelDash($r){return ['dept_head'=>'หัวหน้าแผนก','procurement'=>'ฝ่ายพัสดุ','director'=>'ผู้อำนวยการ'][$r]??$r;}
?>
<!doctype html><html lang="<?=e(current_lang())?>"><head><?php include 'partials/head.php';?></head><body>
<?php include 'partials/nav.php';?>
<main class="container dashboard-v2">
  <section class="dash-title-row">
    <div><h1><?= current_lang()==='th'?'แดชบอร์ดภาพรวม':'Dashboard Overview' ?></h1><p><?= current_lang()==='th'?'ติดตามสถานะการเบิกจ่ายพัสดุ คำสั่งซื้อ และการอนุมัติตามลำดับขั้น':'Monitor material requests, approvals and inventory in one place.' ?></p></div>
    <div class="dash-filters"><div class="select-chip">▦ <?= current_lang()==='th'?'ทุกแผนก':'All Departments' ?>⌄</div><div class="select-chip">▣ <?=date('d M Y')?>⌄</div><?php if(in_array(user()['role_code'],['requester','admin'],true)):?><a class="btn new-main" href="request_new.php">＋ <?= current_lang()==='th'?'สร้างรายการใหม่':'New Request' ?></a><?php endif;?></div>
  </section>

  <section class="metric-grid six">
    <a class="metric-card metric-link" href="requests.php" title="ดูรายการคำขอทั้งหมด"><div class="metric-icon sand">▤</div><div><span><?= current_lang()==='th'?'คำขอเบิกทั้งหมด':'Total Requisitions' ?></span><strong><?=$totalRequests?></strong><small>↗ <?= current_lang()==='th'?'กดเพื่อดูรายละเอียด':'Click to view details' ?></small></div></a>
    <a class="metric-card metric-link" href="approvals.php" title="ดูรายการรออนุมัติ"><div class="metric-icon gold">⌑</div><div><span><?= current_lang()==='th'?'รออนุมัติ':'Pending Approval' ?></span><strong><?=$pendingRequests?></strong><small class="warn">● <?= current_lang()==='th'?'กดเพื่อดำเนินการ':'Click to process' ?></small></div></a>
    <a class="metric-card metric-link" href="requests.php?status=approved" title="ดูรายการอนุมัติแล้ว"><div class="metric-icon mint">✓</div><div><span><?= current_lang()==='th'?'อนุมัติแล้ว':'Approved' ?></span><strong><?=$approvedRequests?></strong><small class="good">↗ <?=$approvalRate?>% <?= current_lang()==='th'?'กดเพื่อดูรายการ':'Click to view' ?></small></div></a>
    <a class="metric-card metric-link" href="requests.php?status=issued" title="ดูรายการที่จ่ายพัสดุแล้ว"><div class="metric-icon peach">⇢</div><div><span><?= current_lang()==='th'?'จ่ายพัสดุแล้ว':'Issued' ?></span><strong><?=$issuedCount?></strong><small class="good">↗ <?=$issuedRate?>% <?= current_lang()==='th'?'กดเพื่อดูรายการ':'Click to view' ?></small></div></a>
    <a class="metric-card metric-link" href="materials.php?filter=low" title="ดูพัสดุใกล้หมด"><div class="metric-icon rose">!</div><div><span><?= current_lang()==='th'?'พัสดุใกล้หมด':'Low Stock' ?></span><strong><?=$lowStock?></strong><small class="danger">● <?= current_lang()==='th'?'ต่ำกว่า 10 ชิ้น':'Below 10 units' ?><?= $outOfStock>0 ? ' · '.(current_lang()==='th'?'หมดแล้ว ':'Out ').$outOfStock : '' ?></small></div></a>
    <a class="metric-card metric-link" href="materials.php" title="ดูคลังพัสดุ"><div class="metric-icon lavender">▦</div><div><span><?= current_lang()==='th'?'รายการในคลัง':'Inventory Items' ?></span><strong><?=$materialsCount?></strong><small><?= current_lang()==='th'?'กดเพื่อดูคลัง':'Click to open inventory' ?></small></div></a>
  </section>

  <section class="analytics-grid">
    <article class="dash-card spend-card">
      <div class="dash-card-head"><div><h3><?= current_lang()==='th'?'ภาพรวมคำขอ':'Request Overview' ?></h3><p><?= current_lang()==='th'?'จำนวนคำขอในช่วงเวลาล่าสุด':'Recent request activity' ?></p></div><div class="period-select"><?= current_lang()==='th'?'เดือนนี้':'This Month' ?>⌄</div></div>
      <div class="line-chart"><div class="chart-y"><span><?=$monthRequests+6?></span><span><?=$monthRequests+4?></span><span><?=$monthRequests+2?></span><span>0</span></div><div class="chart-area"><div class="grid-lines"></div><svg viewBox="0 0 600 220" preserveAspectRatio="none"><defs><linearGradient id="areaFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#b08362" stop-opacity=".26"/><stop offset="1" stop-color="#b08362" stop-opacity=".02"/></linearGradient></defs><path d="M10 178 L150 150 L290 116 L430 82 L585 45 L585 220 L10 220 Z" fill="url(#areaFill)"/><path d="M10 178 L150 150 L290 116 L430 82 L585 45" fill="none" stroke="#8a6044" stroke-width="3" stroke-linecap="round"/><g fill="#8a6044" stroke="#fff" stroke-width="4"><circle cx="10" cy="178" r="5"/><circle cx="150" cy="150" r="5"/><circle cx="290" cy="116" r="5"/><circle cx="430" cy="82" r="5"/><circle cx="585" cy="45" r="5"/></g></svg><div class="chart-x"><span>01</span><span>08</span><span>15</span><span>22</span><span><?=date('d')?></span></div></div></div>
      <div class="chart-summary"><div><span><?= current_lang()==='th'?'คำขอเดือนนี้':'This Month' ?></span><b><?=$monthRequests?></b></div><div><span><?= current_lang()==='th'?'อนุมัติเดือนนี้':'Approved This Month' ?></span><b><?=$monthApproved?></b></div><div><span><?= current_lang()==='th'?'อัตราอนุมัติ':'Approval Rate' ?></span><b><?=$approvalRate?>%</b></div></div>
    </article>

    <article class="dash-card category-card"><div class="dash-card-head"><div><h3><?= current_lang()==='th'?'คำขอตามแผนก':'Requests by Department' ?></h3><p>Department Overview</p></div></div><div class="donut-layout"><div class="donut"><div class="donut-center"><b><?=$totalRequests?></b><span><?= current_lang()==='th'?'คำขอทั้งหมด':'Total Requests' ?></span></div></div><div class="legend-list"><?php $max=max(1,$totalRequests); foreach($deptStats as $i=>$d): $pct=round($d['total']/$max*100); ?><div><i class="dot d<?=$i?>"></i><span><?=e($d['department'])?></span><b><?=$d['total']?> <small>(<?=$pct?>%)</small></b></div><?php endforeach; if(!$deptStats):?><div><span><?= current_lang()==='th'?'ยังไม่มีข้อมูล':'No data yet' ?></span></div><?php endif;?></div></div><a class="view-link" href="requests.php"><?= current_lang()==='th'?'ดูคำขอทั้งหมด':'View all requests' ?> →</a></article>

    <article class="dash-card pipeline-card"><div class="dash-card-head"><div><h3><?= current_lang()==='th'?'สถานะขั้นตอนการอนุมัติ':'Approval Pipeline' ?></h3><p><?= current_lang()==='th'?'ติดตามการอนุมัติแบบหลายระดับ':'Multi-level workflow status' ?></p></div><a class="view-link top" href="approvals.php"><?= current_lang()==='th'?'ทั้งหมด':'View all' ?> →</a></div><div class="pipeline-list"><?php if($pipeline): foreach($pipeline as $level=>$p): ?><div class="pipe-row"><div class="pipe-icon"><?=$level?></div><div class="pipe-text"><b><?=e(roleLabelDash($p['role']))?></b><span><?= current_lang()==='th'?'ขั้นที่':'Level' ?> <?=$level?></span></div><div class="pipe-count"><b><?=$p['pending']?></b><small><?= current_lang()==='th'?'รอดำเนินการ':'Pending' ?></small></div></div><?php endforeach; else: ?><div class="empty mini-empty"><?= current_lang()==='th'?'ยังไม่มีข้อมูลขั้นตอนอนุมัติ':'No approval workflow data yet' ?></div><?php endif;?></div></article>
  </section>

  <section class="bottom-grid">
    <article class="dash-card recent-card"><div class="dash-card-head"><div><h3><?= current_lang()==='th'?'รายการล่าสุด':'Recent Requests' ?></h3><p>Latest Requisitions</p></div><a class="view-link top" href="requests.php"><?= current_lang()==='th'?'ดูทั้งหมด':'View all' ?> →</a></div><div class="table-wrap modern-table"><table class="table"><thead><tr><th><?= current_lang()==='th'?'เลขที่คำขอ':'Request No.' ?></th><th><?= current_lang()==='th'?'ผู้ขอ':'Requester' ?></th><th><?= current_lang()==='th'?'แผนก':'Department' ?></th><th><?= current_lang()==='th'?'วันที่':'Date' ?></th><th><?= current_lang()==='th'?'สถานะ':'Status' ?></th></tr></thead><tbody><?php foreach($recent as $r):?><tr onclick="location.href='request_view.php?id=<?=$r['id']?>'" style="cursor:pointer"><td><b><?=e($r['request_no'])?></b></td><td><?=e($r['requester'])?></td><td><?=e($r['department'])?></td><td><?=e(date('d M Y',strtotime($r['created_at'])))?></td><td><span class="badge <?=e($r['status'])?>"><?=e(status_text($r['status']))?></span></td></tr><?php endforeach;?></tbody></table><?php if(!$recent):?><div class="empty"><?=e(t('empty_requests'))?></div><?php endif;?></div></article>
    <article class="dash-card quick-panel"><div class="dash-card-head"><div><h3><?= current_lang()==='th'?'ทางลัด':'Quick Actions' ?></h3><p>Quick actions</p></div></div><div class="quick-grid v2"><a class="quick-card" href="request_new.php"><div class="quick-icon">＋</div><div><b><?= current_lang()==='th'?'สร้างใบเบิก':'Create Request' ?></b><span><?= current_lang()==='th'?'ส่งคำขอใหม่':'Submit a new request' ?></span></div></a><a class="quick-card" href="requests.php"><div class="quick-icon">▤</div><div><b><?= current_lang()==='th'?'รายการใบเบิก':'Requests' ?></b><span><?= current_lang()==='th'?'ติดตามสถานะ':'Track status' ?></span></div></a><a class="quick-card" href="materials.php"><div class="quick-icon">▦</div><div><b><?= current_lang()==='th'?'คลังพัสดุ':'Inventory' ?></b><span><?=$materialsCount?> <?= current_lang()==='th'?'รายการ':'items' ?></span></div></a><a class="quick-card" href="approvals.php"><div class="quick-icon">✓</div><div><b><?= current_lang()==='th'?'อนุมัติรายการ':'Approvals' ?></b><span><?=$pendingRequests?> <?= current_lang()==='th'?'รายการรอ':'pending' ?></span></div></a></div></article>
  </section>

  <section class="vendor-dashboard-grid">
    <article class="dash-card vendor-dashboard-card"><div class="dash-card-head"><div><h3><?= current_lang()==='th'?'ผู้ขายยอดนิยม':'Top Vendors' ?></h3><p><?= current_lang()==='th'?'จัดอันดับตามยอดสั่งซื้อ':'Ranked by purchase order value' ?></p></div><a class="view-link top" href="vendors.php"><?= current_lang()==='th'?'ดูทั้งหมด':'View all' ?> →</a></div>
      <div class="vendor-list compact"><?php if($topVendors): foreach($topVendors as $i=>$v): $maxSpend=max(1,(float)$topVendors[0]['total_spend']); $width=max(8,round((float)$v['total_spend']/$maxSpend*100)); ?><div class="vendor-row"><div class="rank"><?=$i+1?></div><div class="vendor-info"><b><?=e($v['name'])?></b><span><?=$v['po_count']?> <?= current_lang()==='th'?'คำสั่งซื้อ':'purchase orders' ?></span></div><div class="vendor-bar"><i style="width:<?=$width?>%"></i></div><div class="vendor-total"><b>฿ <?=number_format((float)$v['total_spend'],0)?></b></div></div><?php endforeach; else:?><div class="empty mini-empty"><?= current_lang()==='th'?'ยังไม่มีข้อมูลผู้ขาย':'No vendor data yet' ?></div><?php endif;?></div>
    </article>
  </section>

  <section class="dash-footer-metrics"><div><i>◷</i><span><?= current_lang()==='th'?'อัตราอนุมัติ':'Approval Rate' ?><b><?=$approvalRate?>%</b></span></div><div><i>✓</i><span><?= current_lang()==='th'?'อนุมัติเดือนนี้':'Approved This Month' ?><b><?=$monthApproved?></b></span></div><div><i>▦</i><span><?= current_lang()==='th'?'พัสดุในคลัง':'Active Materials' ?><b><?=fmt_number($totalStock)?></b></span></div><div><i>!</i><span><?= current_lang()==='th'?'พัสดุใกล้หมด':'Low Stock Alert' ?><b><?=$lowStock?></b></span></div><div><i>↗</i><span><?= current_lang()==='th'?'จ่ายพัสดุแล้ว':'Issued Rate' ?><b><?=$issuedRate?>%</b></span></div></section>
</main>
</div></div><script>function toggleSidebar(){document.getElementById('sidebar').classList.toggle('open')}</script></body></html>
