<?php require 'config.php';role_required(['procurement','admin']);if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf();$rid=(int)$_POST['request_id'];$pdo=db();$pdo->beginTransaction();try{$s=$pdo->prepare("SELECT * FROM requests WHERE id=? FOR UPDATE");$s->execute([$rid]);$r=$s->fetch();if(!$r||$r['status']!=='approved')throw new Exception(current_lang()==='th'?'ใบเบิกต้องอนุมัติครบทุกขั้นก่อนจ่าย':'Requisition must complete all approvals before issuing.');$it=$pdo->prepare("SELECT ri.*,m.stock,m.name FROM request_items ri JOIN materials m ON m.id=ri.material_id WHERE ri.request_id=?");$it->execute([$rid]);$items=$it->fetchAll();foreach($items as $x){ if((float)$x['stock']<=0) throw new Exception((current_lang()==='th'?'พัสดุหมด ไม่สามารถจ่ายหรือยืนยันรายการได้: ':'Out of stock, cannot issue: ').$x['name']); if((float)$x['stock']<(float)$x['qty']) throw new Exception((current_lang()==='th'?'สต็อกไม่พอ: ':'Insufficient stock: ').$x['name']); }$pdo->prepare("INSERT INTO issues(request_id,issuer_id,note) VALUES(?,?,?)")->execute([$rid,user()['id'],trim($_POST['note']??'')]);$iid=(int)$pdo->lastInsertId();$ii=$pdo->prepare("INSERT INTO issue_items(issue_id,material_id,qty) VALUES(?,?,?)");$up=$pdo->prepare("UPDATE materials SET stock=stock-? WHERE id=?");$mv=$pdo->prepare("INSERT INTO stock_movements(material_id,movement_type,qty,balance_after,reference_type,reference_id,user_id,note) SELECT id,'OUT',?,stock-?,'ISSUE',?,?,? FROM materials WHERE id=?");foreach($items as $x){$ii->execute([$iid,$x['material_id'],$x['qty']]);$mv->execute([$x['qty'],$x['qty'],$iid,user()['id'],trim($_POST['note']??''),$x['material_id']]);$up->execute([$x['qty'],$x['material_id']]);}$pdo->prepare("UPDATE requests SET status='issued' WHERE id=?")->execute([$rid]);log_action($rid,user()['id'],'ISSUE','Materials issued');$pdo->commit();flash('ok',current_lang()==='th'?'จ่ายพัสดุเรียบร้อย':'Materials issued successfully.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error',$e->getMessage());}redirect('issue.php');}$msg=flash();
$pdo=db();
$rows=$pdo->query("SELECT r.*,u.name requester FROM requests r JOIN users u ON u.id=r.requester_id WHERE r.status='approved' ORDER BY r.id")->fetchAll();
$itemsByRequest=[];
foreach($rows as $r){
  $st=$pdo->prepare("SELECT ri.*,m.code,m.name,m.unit,m.stock,m.min_stock FROM request_items ri JOIN materials m ON m.id=ri.material_id WHERE ri.request_id=? ORDER BY m.name");
  $st->execute([$r['id']]); $itemsByRequest[$r['id']]=$st->fetchAll();
}
?><!doctype html><html lang="<?=e(current_lang())?>"><head><?php include 'partials/head.php';?></head><body><?php include 'partials/nav.php';?><main class="container">
<div class="page-head"><div><h2>📤 <?=e(t('issue'))?></h2><p><?= current_lang()==='th'?'เลือกใบเบิกที่อนุมัติแล้วเพื่อตัดจ่ายจากคลัง':'Issue approved requests and automatically deduct inventory.'?></p></div></div>
<?php if($msg):?><div class="alert <?=e($msg[0])?>"><?=e($msg[1])?></div><?php endif;?>
<?php if($rows): foreach($rows as $r): $items=$itemsByRequest[$r['id']]; $canIssue=true; foreach($items as $x) if((float)$x['stock']<=0 || (float)$x['stock']<(float)$x['qty']) $canIssue=false; ?>
<form method="post" class="panel issue-card">
<input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="request_id" value="<?=$r['id']?>">
<div class="panel-head"><div><h3><a href="request_view.php?id=<?=$r['id']?>">📄 <?=e($r['request_no'])?></a></h3><span><?=e(t('requester'))?>: <?=e($r['requester'])?> · <?=e(t('department'))?>: <?=e($r['department'])?></span></div><span class="badge approved">อนุมัติแล้ว</span></div>
<div class="table-wrap"><table class="table"><thead><tr><th>รหัส</th><th>พัสดุ</th><th>จำนวนที่ขอ</th><th>คงเหลือในคลัง</th><th>สถานะ</th></tr></thead><tbody>
<?php foreach($items as $x): $isOut=(float)$x['stock']<=0; $enough=!$isOut && (float)$x['stock']>=(float)$x['qty']; $low=(!$isOut && (float)$x['stock']<10); ?><tr><td><?=e($x['code'])?></td><td><b><?=e($x['name'])?></b><br><small><?=e($x['unit'])?></small></td><td><?=fmt_number($x['qty'])?> <?=e($x['unit'])?></td><td class="<?=(!$enough||$isOut)?'stock-low':''?>"><b><?=fmt_number($x['stock'])?></b> <?=e($x['unit'])?><?php if($isOut):?> <span class="out-badge">หมดแล้ว</span><?php elseif($low):?> <span class="low-badge">ใกล้หมด</span><?php endif;?></td><td><?php if($isOut):?><span class="stock-no">✕ หมดแล้ว ไม่สามารถจ่าย</span><?php elseif($enough):?><span class="stock-ok">✓ พร้อมจ่าย</span><?php else:?><span class="stock-no">✕ สต็อกไม่พอ</span><?php endif;?></td></tr><?php endforeach;?>
</tbody></table></div>
<div class="issue-actions"><div><label>หมายเหตุการจ่าย</label><textarea name="note" placeholder="เช่น ผู้รับพัสดุ / รายละเอียดเพิ่มเติม"></textarea></div><button class="success" <?=!$canIssue?'disabled title="สต็อกไม่เพียงพอ"':''?>>✓ ยืนยันจ่ายพัสดุ</button></div>
<?php if(!$canIssue):?><div class="alert error" style="margin-top:12px">⚠️ มีรายการที่สต็อกไม่พอหรือหมดแล้ว ระบบไม่อนุญาตให้ยืนยันจ่ายพัสดุ กรุณาเติมสต็อกก่อน</div><?php endif;?>
</form>
<?php endforeach; else:?><div class="panel empty">ไม่มีรายการที่พร้อมจ่ายในขณะนี้</div><?php endif;?>
</main></div></div></body></html>